export const CREATE_COMMENT="CREATE_COMMENT";
export const LIKE_COMMENT="LIKE_COMMENT";
export const DELETE_COMMENT="DELETE_COMMENT";
export const UPDATE_COMMENT="UPDATE_COMMENT";
export const GET_POST_COMMENT="GET_POST_COMMENT";