export const GET_DASHBOARD_ANALYTICS = "GET_DASHBOARD_ANALYTICS";
export const GET_POST_ANALYTICS = "GET_POST_ANALYTICS";
export const GET_LIKE_ANALYTICS = "GET_LIKE_ANALYTICS";
export const GET_USER_ANALYTICS = "GET_USER_ANALYTICS";
export const GET_ALL_USERS = "GET_ALL_USERS";
export const BAN_USER = "BAN_USER";
export const UNBAN_USERS = "UNBAN_USERS";